### ISSUE TITLE
Casc: setting the project permissions as code

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#1022]
Have a way to define the project permissions as code using the Casc framework.

The main issue is that the projects listed in the configuration may or may not exist at the time the configuration is run. Therefore, the Casc should be very conservative and allow for non-existing projects (and groups).

The configuration is based on groups first, since they may be assigned to several projects. For example:

```yaml
ontrack:
   admin:
      project-permissions:
         - group: my-group
            role: VALIDATION_MANAGER
            projects:
               - project-1
               - project-2
         - group: my-group
           role: PROJECT_OWNER
           projects:
              - project-3
```

Groups (and projects) can be duplicated. In case of conflict, the last permission will be taken into account.
