### ISSUE TITLE
Configuration as code for the entity-level subscription

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#1041]
It's possible to use CasC to configure the global subscriptions, but it should be possible to configure the entity-level subscriptions using the same model than for the project-level permissions.

Example of such syntax:

```yaml
ontrack:
   extensions:
      notifications:
         entity-subscriptions:
             - entity:
                  project: xxx
                  branch: xxx
                  promotion: xxx
               subscriptions:
                - events:
                    - new_promotion_run
                  keywords: "GOLD main"
                  channel: mock
                  channel-config:
                    target: "#$target"
```

Only the following entities will be supported: project, branch, promotion, validation.
