### ISSUE TITLE
Notifications: Casc improvements for the entity subscriptions

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#1045]
* logging about the actions (debug level, but info for the non existing entities/subscriptions)
* test the combinations between entities:

```yaml
ontrack:
  extensions:
    notifications:
      entity-subscriptions:
        - entity:
            project: prj
            branch: main
          subscriptions:
            - events:
                - auto-versioning-error
                - auto-versioning-success
                - auto-versioning-pr-merge-timeout-error
              keywords: ""
              channel: slack
              channel-config:
                channel: "#test"
        - entity:
            project: prj
            branch: main
          subscriptions:
            - events:
                - new_promotion_run
              keywords: "GOLD"
              channel: slack
              channel-config:
                channel: "#test"
```

* test the sync when changing only the configuration for the channel
