### ISSUE TITLE
Auto versioning: configuration of notifications

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#1047]
Adapt the auto versioning configuration model so that notification subscriptions can be directly setup in the configuration file.

For example:

```yaml
configurations:
  - sourceProject: ...
    notifications:
       -  scope:
            - all
          channel: slack
          config:
            channel: "#my-channel"
```

The scope is a list of strings (`all` by default) which can be: `success`, `pr-timeout` or `error`.
