### ISSUE TITLE
Auto-versioning: NOP property type

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#1107]
In some cases, the version is too difficult to update to be processed by the Ontrack default property types (property, yaml, etc.) and must be delegated entirely to the post processing.

This issue introduces the `nop` property type to allow such a "no operation" processing by Ontrack, relying only on the post processing. This would look like:

```yaml
dependencies:
  - project: my-project
    branch: my-branch
    promotion: SILVER
    path: my-target-file
    propertyType: nop
    property: ''
    postProcessing: jenkins
    postProcessingConfig:
      dockerImage: ...
      dockerCommand: ...
```

ℹ️ `path` and `property` should not be required any longer and left there only for information

The auto versioning implementation must be adapted to allow the initial source code not to be changed (by default, if no change is detected by Ontrack, we drop the processing altogether).
