### ISSUE TITLE
Auto-versioning: option to validate the source build on auto versioning being complete

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#1109]
Given a `dependency` being using by a `project`, and `project` auto versioning `dependency`, we may want the `dependency` build being upgraded to receive a validation.

This could look like, in the `project`:

```yaml
dependencies:
  - project: dependency
    # ...
    backValidation: <some validation>
```

The value for `backValidation` can be an explicit validation stamp in the source `dependency` or can be `auto`. In the latter case, the name of the validation stamp will be `auto-versioned-<project>`.
