### ISSUE TITLE
Auto-versioning: possibility to specify reviewers for auto versioning pull requests

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#1115]
When auto versioning is set up with auto approval disabled - `autoApproval: false` -, no default reviewer is setup (unless the SCM and repositories are configured accordingly).

Make possible to configure the auto versioning to specify a list of reviewers as code. For example:

```yaml
dependencies:
  - project: ...
    # ...
    autoApproval: false
    approvers:
      - user1
      - user2
```

This list of approvers will be set for all types of pull requests (auto approved or not). The users ID will be SCM (GitHub, Bitbucket, ...) specific.
