### ISSUE TITLE
In the ontrack-validation notification, allow to specify a run time

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#1304]
Additionally, have a template extension to get the time of execution of the current workflow so that it can be used in the computation.

For example:

```yaml
channel: ontrack-validation
channelConfig:
   validation: my-validation
   runTime: '${#.sinceSeconds(workflowInfo.start)}'
```
