### ISSUE TITLE
If a workflow node execution times out, the workflow instance is not marked as stopped or in error

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#1305]
Given a workflow like:

```yaml
name: Test
nodes:
  - id: jenkins
    executorId: jenkins
    data:
      channel: jenkins
      channelConfig:
        config: ...
        job: ...
        callMode: SYNC
        timeout: 1800
  # ...
```

If the `jenkins` node execution times out, the corresponding notification record is correctly registered as having timeout and marked as error.

However, the workflow itself remains in Running state and the `jenkins` node execution as Started.

Upon a failure, mark he node as failed and dequeue all nodes.

Have a button in the workflow to stop a workflow.
