### ISSUE TITLE
Supporting several paths in auto-versioning configurations

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#1343]
For example:

```yaml
dependencies:
  - path: ...
    propertyType: yaml
    property: ...
    # additional paths
    additionalPaths:
      - path: Dockerfile
        regex: ...
```

The single `path` remains required since it’s the most common use case, and acts as a reference.

The `versionSource` must be defined at top level (or by default) but can be overridden at path level (for write only).
