### ISSUE TITLE
Slot description in Casc is used every slot

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#1434]
Given a Casc like:

```
ontrack:
  config:
    environments:
      slots:
       - project: test
         description: My description
         environments:
           - name: staging
           - name: production
```

two slots are managed for the `test` project, one for `staging`, one for `production`.

However, the description will be applied to both of them.

Change the behaviour:

* add a `description` in `environments[]` which takes precedence if provided
* if having a `description` at slot level, add the environment name as a suffix
* if not having a `description` at slot level, don't set a description
