### ISSUE TITLE
Document metrics

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#258]
* [x] list of metrics
* [x] Graphite support
* [x] Documentation of installation and parameters
* [x] InfluxDB support (see #257)

**Comment by dcoraboeuf** [comment]
See https://github.com/nemerosa/ontrack/wiki/Monitoring

**Comment by dcoraboeuf** [comment]
A sample compose file:

```yaml
# InfluxDB container
influxdb:
  image: tutum/influxdb:0.9
# Grafana container
grafana:
  image: tutum/grafana:latest
  ports:
    - "80"
  links:
    - "influxdb:influxdb"
  environment:
    INFLUXDB_HOST: influxdb
    INFLUXDB_NAME: grafana
    HTTP_PASS: admin
# Ontrack container
ontrack:
  image: nemerosa/ontrack:2.15.2
  links:
     - "influxdb:influxdb"
  ports:
     - "8080"
  environment:
    ONTRACK_CONFIG_INFLUXDBHOST: influxdb
    ONTRACK_CONFIG_INFLUXDBPORT: 8083
```

Will be possible when #257 is fixed.
