### ISSUE TITLE
Can't run version 3.1.2 with docker following docs

### ISSUE THREAD

**Issue by alitheg** [nemerosa/ontrack#565]
The docs on the website point to v2.32.12, so you have to grab the 3.1.2 docs from the GitHub release page specifically. The commands there instruct you to `docker run` the without a tag, so docker grabs the `:latest` tag, which also appears to be v2. When I explicitly pull v3.1.2 of the docker image, I get an error connecting to postgres trying to start it - do I need to have a postgres sever running separately in order to run the latest version?

**Comment by dcoraboeuf** [comment]
Hi,

The fact that the 3.x documentation does not appear at http://nemerosa.github.io/ontrack/ is clearly an anomaly. I'll have a look.

For the other problem, the version 3.x offers only the support for Postgres and I'm afraid it is not very documented right now :(

So yes, for version 3, you need a separate Postgres database. What I do in production is to use Docker Compose, as in https://github.com/nemerosa/ontrack/blob/release/3.1/gradle/compose/docker-compose-prod.yml (together with the base files at https://github.com/nemerosa/ontrack/tree/release/3.1/gradle/compose).

I'll leave this ticket open to better document the deployment of the version 3. When time allows :(

Best regards,
Damien.

**Comment by dcoraboeuf** [comment]
The next version 3 will include:

* a slightly better documentation
* a Docker Hub `3` version (so, not `latest`)

In the meantime, you can already use the following Docker Compose file to get you started (the one in the future released documentation will include `3` instead of `3.1.2`):

```yaml
version: "2.1"

services:
  # Ontrack container
  ontrack:
    image: nemerosa/ontrack:3.1.2
    environment:
        PROFILE: prod
    links:
      - "postgresql:postgresql"
    ports:
      - "8080:8080"

  # Postgresql database
  postgresql:
    image: postgres:9.5.2
    environment:
      POSTGRES_DB      : ontrack
      POSTGRES_USER    : ontrack
      POSTGRES_PASSWORD: ontrack
    ports:
      - "5432"
```

You can then run:

```bash
docker-compose up -d
```

After some time, Ontrack is available at http://localhost:8080
