### ISSUE TITLE
Configuration as code

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#860]
Ontrack should have a way to be configured using a set of script/configuration files, without relying on the API and Ontrack being started.

This should start with the settings and security settings.

The format of these files could be YAML.

There must be a way to reload those files at runtime, in an idempotent way.

Example: to configure a Keycloak authentication:

```yaml
ontrack:
    config:
        security:
            oicd:
                - id: keycloak-realm
                  name: My Keycloak
                  description: ...
                  issuer-id: <...>
                  client-id: <...>
                  group-filter: ontrack-.*
```
