### ISSUE TITLE
[experimental] Preprocessing of Casc files for reading secrets

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#954]
As of 4.1.23, Casc files can contain secrets in plain text. By using the Ontrack Helm Chart and using Casc fragments stored in secrets, we can store secrets in a safer way but the procedure in cumbersome.

Another way would be to reference secrets directly from the plain Casc files. For example:

```yaml
ontrack:
  config:
    jenkins:
      - name: my-jenkins
        url: my-url
        username: {{ secret.my-jenkins.username }}
        password: {{ secret.my-jenkins.password }}
```

`{{secret.my-jenkins.username}}` would refer to the `username` property of a secret called `my-jenkins`.

By default, several implementations of Casc secret access would be available:

* mapping to environment variables - `secret.my-jenkins.username` --> `SECRET_MY_JENKINS_USERNAME`
* mapping to files - `secret.my-jenkins.username` --> `<root>/my-jenkins/username`

Both implementations can easily be mapped to Kubernetes deployments.
