### ISSUE TITLE
Casc: support for indentation when expanding secrets in Casc files

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#956]
Given a Casc file like:

```yaml
ontrack:
  config:
    github:
      - appPrivateKey: |-
          {{ secret.secret.app-private-key }}
```

If `app-private-key` is on several lines, we expect the output to respect these multilines as well.
