### ISSUE TITLE
Casc: associating groups to role

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#959]
Allows group to be mapped to roles:

```yaml
ontrack:
  admin:
    group-permissions:
      - group: CI
        role: AUTOMATION
```
