### ISSUE TITLE
[EXPERIMENTAL] GitHub ingestion: configuration of project & branch with properties

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#967]
In the `ingestion.yaml` file, allow the project & the branch to be configured as code (CasC). This includes in particular the configuration of some properties.

The CasC module must be extended to address project entities.

Example of a configuration, to set the stale property on a branch:

```
casc:
  branch:
    properties:
      staleProperty:
        disablingDuration: 30
        deletingDuration: 0
        promotionsToKeep:
          - GOLD
        includes: "release/.*"
        excludes: "release/1.*"
```
