### ISSUE TITLE
GitHub Actions ingestion: filtering of workflows

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#969]
In the `ingestion.yml` file, give the possibility to exclude some workflows:

```yaml
workflows:
  filter:
    includes: ".*"
    excludes: ""
```
