### ISSUE TITLE
GitHub Ingestion: configuration of the validation stamps data types

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#977]
Use the `ingestion.yml` file to configure the data types for the validation stamps.

For example:

```yaml
validations:
  - name: my-validation
    description: My validation
    data-type:
       type: net.nemerosa.ontrack.extension.general.validation.TestSummaryValidationDataType
       config:
          warningIfSkipped: true
```

Shortcuts for well-know types are available:

```yaml
validations:
  - name: my-validation
    description: My validation
    data-type:
       type: test-summary
       config:
          warningIfSkipped: true
```
