### ISSUE TITLE
GitHub Ingestion: configuration of the validation stamps and promotion images

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#978]
Use the `ingestion.yml` file to configure the images for the promotion levels & validation stamps. This can be done by pointing to an image in a GitHub repository (it must be in the same server, as designed by the project GitHub configuration).

For example:

```yaml
validations:
  - name: my-validation
    description: My validation
    image: org/repo/validations/my-validation.png
promotions:
  - name: my-promotion
    image: org/repo/promotions/my-promotion.png
```
