### ISSUE TITLE
GitHub Ingestion: tagging strategies

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#986]
In some workflows, the tag event is correctly sent but since the tag is associated to a commit created by the release process, and the previous commit (which was created by the build we actually want to label) is not found.

A `push` tag event contains a `base_ref` which indicates the Git branch on which it has been created. This allows to identify the Ontrack branch.

On this branch, we can look for the most recent build having the following properties:

* having a Git commit property
* having a given promotion

This fallback behavior must be defined in the ingestion configuration:

```yaml
tagging:
   strategies:
      - type: promotion
         parameters: |-
            name: BRONZE
```

Several strategies may be defined. The first match takes precedence. By default, the `commit-property` strategy is applied by default, unless `commit-strategy` is set to `false` (it can always be re-applied as a regular strategy):

```yaml
tagging:
   commit-strategy: false
   strategies:
      - type: promotion
         config: |-
            name: BRONZE
      - type: commit-strategy
```
